name: naija
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74623
title: 'for what we were, are and will be'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9684635726734996
  lightness: 0.4406782714650035
  saturation: 0.6155617504846305
  rhythmicContrast: 0.5744570028036833
purpose: []
